#include "TestsHeader.hpp"

TEST_CASE( "Velocity vector generated by Smirnov algorythm", "[SmirnovAlgorythm]" )
{
	double* space_point_test = new double[3] {1.,1.,1.};
	STG::VelocitySmirnov test_vector(space_point_test, 0);
	STG::Generator<std::mt19937, std::normal_distribution<>> genengine(0, 1, 2134);
	test_vector.generate(&genengine);

	CHECK(
		compare_vectors( 
			test_vector.get_vector().get_values(), 
			{-1.4648215920903935, 2.5518080004779593, -0.22080433331401358}
			)
	);
}